<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.adv.qa.selenium.tests.currency.A006_Company_DefinitionTest" tests="1" time="133.231" ignored="0" failures="1" timestamp="08 Mar 2017 13:19:04 GMT" skipped="0" hostname="ChetnaM-PC" errors="0">
  <testcase name="verify" time="133.231" classname="com.adv.qa.selenium.tests.currency.A006_Company_DefinitionTest">
    <failure type="java.lang.AssertionError" message="New company id IM not displayed in the list expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: New company id IM not displayed in the list expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.adv.qa.selenium.framework.Assert.assertTrue(Assert.java:43)
	at com.adv.qa.selenium.tests.currency.A006_Company_DefinitionTest.verify(A006_Company_DefinitionTest.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- verify -->
</testsuite> <!-- com.adv.qa.selenium.tests.currency.A006_Company_DefinitionTest -->
